// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Appointment
{
    public string AppointmentId { get; set; }

    public string UserDriverId { get; set; }

    public string BatterySwapStationId { get; set; }

    public string Note { get; set; }

    public DateOnly DateBooking { get; set; }

    public TimeOnly TimeBooking { get; set; }

    public string SubscriptionId { get; set; }

    public string Status { get; set; }

    public DateTime CreateBookingAt { get; set; }

    public string TransactionId { get; set; }

    public virtual BatterySwapStation BatterySwapStation { get; set; }

    public virtual ICollection<PillarSlot> PillarSlots { get; set; } = new List<PillarSlot>();

    public virtual Subscription Subscription { get; set; }

    public virtual Transaction Transaction { get; set; }

    public virtual User UserDriver { get; set; }
}