// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class BatterySwapStation
{
    public string BatterySwapStationId { get; set; }

    public string BatterySwapStationName { get; set; }

    public string Address { get; set; }

    public decimal LocationLat { get; set; }

    public decimal LocationLng { get; set; }

    public int NumberOfPillar { get; set; }

    public string Status { get; set; }

    public TimeOnly OpenTime { get; set; }

    public TimeOnly CloseTime { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Battery> Batteries { get; set; } = new List<Battery>();

    public virtual ICollection<BatterySwapPillar> BatterySwapPillars { get; set; } = new List<BatterySwapPillar>();

    public virtual ICollection<BatterySwap> BatterySwaps { get; set; } = new List<BatterySwap>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<StationStaff> StationStaffs { get; set; } = new List<StationStaff>();

    public virtual ICollection<TransferLog> TransferLogNewLocations { get; set; } = new List<TransferLog>();

    public virtual ICollection<TransferLog> TransferLogOldLocations { get; set; } = new List<TransferLog>();
}