// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class BatterySession
{
    public int SessionId { get; set; }

    public string BatteryId { get; set; }

    public string EventType { get; set; }

    public decimal? SocDelta { get; set; }

    public decimal? EnergyDeltaWh { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual Battery Battery { get; set; }
}