// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Battery
{
    public string BatteryId { get; set; }

    public string BatterySwapStationId { get; set; }

    public decimal Capacity { get; set; }

    public decimal Soc { get; set; }

    public decimal Soh { get; set; }

    public string BatteryStatus { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<BatterySession> BatterySessions { get; set; } = new List<BatterySession>();

    public virtual ICollection<BatterySwap> BatterySwapBatteryIns { get; set; } = new List<BatterySwap>();

    public virtual ICollection<BatterySwap> BatterySwapBatteryOuts { get; set; } = new List<BatterySwap>();

    public virtual BatterySwapStation BatterySwapStation { get; set; }

    public virtual ICollection<PillarSlot> PillarSlots { get; set; } = new List<PillarSlot>();

    public virtual ICollection<TransferLog> TransferLogs { get; set; } = new List<TransferLog>();
}