// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class BatterySwapPillar
{
    public string BatterySwapPillarId { get; set; }

    public string BatterySwapStationId { get; set; }

    public int PillarCapacity { get; set; }

    public virtual BatterySwapStation BatterySwapStation { get; set; }

    public virtual ICollection<PillarSlot> PillarSlots { get; set; } = new List<PillarSlot>();
}