// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class BatterySwap
{
    public string SwapHistoryId { get; set; }

    public string SubscriptionId { get; set; }

    public string BatterySwapStationId { get; set; }

    public string BatteryOutId { get; set; }

    public string BatteryInId { get; set; }

    public DateOnly SwapDate { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public DateTime CreateAt { get; set; }

    public virtual Battery BatteryIn { get; set; }

    public virtual Battery BatteryOut { get; set; }

    public virtual BatterySwapStation BatterySwapStation { get; set; }

    public virtual Subscription Subscription { get; set; }
}