// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class DriverVehicle
{
    public string Vin { get; set; }

    public string UserDriverId { get; set; }

    public string VehicleModel { get; set; }

    public int NumberOfBattery { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User UserDriver { get; set; }
}