// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Fee
{
    public int FeeId { get; set; }

    public string PlanId { get; set; }

    public string UserAdminId { get; set; }

    public string TypeOfFee { get; set; }

    public decimal Amount { get; set; }

    public string Unit { get; set; }

    public decimal MinValue { get; set; }

    public decimal MaxValue { get; set; }

    public string CalculationMethod { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual Plan Plan { get; set; }

    public virtual User UserAdmin { get; set; }
}