// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Plan
{
    public string PlanId { get; set; }

    public string UserAdminId { get; set; }

    public string PlanName { get; set; }

    public int? DurationDays { get; set; }

    public int? NumberOfBattery { get; set; }

    public decimal? MileageBaseUsed { get; set; }

    public int? SwapLimit { get; set; }

    public decimal? Price { get; set; }

    public string Status { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual ICollection<Fee> Fees { get; set; } = new List<Fee>();

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();

    public virtual User UserAdmin { get; set; }
}