// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Rating
{
    public int RatingId { get; set; }

    public string UserDriverId { get; set; }

    public string BatterySwapStationId { get; set; }

    public int RatingScore { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual BatterySwapStation BatterySwapStation { get; set; }

    public virtual User UserDriver { get; set; }
}