// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public string UserAdminId { get; set; }

    public string UserStaffId { get; set; }

    public string UserDriverId { get; set; }

    public int ReportTypeId { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime ProcessesAt { get; set; }

    public virtual ReportType ReportType { get; set; }

    public virtual User UserAdmin { get; set; }

    public virtual User UserDriver { get; set; }

    public virtual User UserStaff { get; set; }
}