// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class ReportType
{
    public int ReportTypeId { get; set; }

    public string ReportTypeName { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}