// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class StationStaff
{
    public int StationStaffId { get; set; }

    public string UserStaffId { get; set; }

    public string BatterySwapStationId { get; set; }

    public TimeOnly ShiftStart { get; set; }

    public TimeOnly ShiftEnd { get; set; }

    public virtual BatterySwapStation BatterySwapStation { get; set; }

    public virtual User UserStaff { get; set; }
}