// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Subscription
{
    public string SubscriptionId { get; set; }

    public string PlanId { get; set; }

    public string UserDriverId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public decimal? CurrentMileage { get; set; }

    public int? RemainingSwap { get; set; }

    public string Status { get; set; }

    public DateTime? CreateAt { get; set; }

    public string PreviousSubscriptionId { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<BatterySwap> BatterySwaps { get; set; } = new List<BatterySwap>();

    public virtual Plan Plan { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual User UserDriver { get; set; }
}