// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class TransferLog
{
    public int TransferId { get; set; }

    public string OldLocationId { get; set; }

    public string NewLocationId { get; set; }

    public string BatteryId { get; set; }

    public string Reason { get; set; }

    public string TransferStatus { get; set; }

    public string UserAdminId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual BatterySwapStation NewLocation { get; set; }

    public virtual BatterySwapStation OldLocation { get; set; }

    public virtual User UserAdmin { get; set; }
}