// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class User
{
    public string UserId { get; set; }

    public string UserName { get; set; }

    public string UserPasswordHash { get; set; }

    public string UserEmail { get; set; }

    public string UserTele { get; set; }

    public string UserRole { get; set; }

    public string UserAddress { get; set; }

    public string SupervisorId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<DriverVehicle> DriverVehicles { get; set; } = new List<DriverVehicle>();

    public virtual ICollection<Fee> Fees { get; set; } = new List<Fee>();

    public virtual ICollection<User> InverseSupervisor { get; set; } = new List<User>();

    public virtual ICollection<Plan> Plans { get; set; } = new List<Plan>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<Report> ReportUserAdmins { get; set; } = new List<Report>();

    public virtual ICollection<Report> ReportUserDrivers { get; set; } = new List<Report>();

    public virtual ICollection<Report> ReportUserStaffs { get; set; } = new List<Report>();

    public virtual ICollection<StationStaff> StationStaffs { get; set; } = new List<StationStaff>();

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();

    public virtual User Supervisor { get; set; }

    public virtual ICollection<Transaction> TransactionCreatedByNavigations { get; set; } = new List<Transaction>();

    public virtual ICollection<Transaction> TransactionUserDrivers { get; set; } = new List<Transaction>();

    public virtual ICollection<TransferLog> TransferLogs { get; set; } = new List<TransferLog>();
}